version: "3"

services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    restart: unless-stopped
    env_file:
      - db/sqlserver.env
      - db/sapassword.env
    volumes:
      - sqlsystem:/var/opt/mssql/
      - sqldata:/var/opt/sqlserver/data
      - sqllog:/var/opt/sqlserver/log
      - sqlbackup:/var/opt/sqlserver/backup
    ports:
      - "1433:1433"
  web:
    build: .
    restart: unless-stopped
    depends_on:
      - db
    environment:
      - "NODE_ENV=development"
    env_file:
      - .env
    ports:
      - "${HOST_PORT:-8088}:3000"
  pdf:
    image: hassananv/weasyprint
    ports:
      - 5001:5001
volumes:
  sqlsystem:
  sqldata:
  sqllog:
  sqlbackup:
